{% set name = "mdal-python" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ViRGIS-Team/mdal-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: bbaeabced6df7f6ff9ab727b29b4edee2f206b203791269d2a79167e7812b421
  
build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<310]
 
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - cmake
    - python
    - pip
  host:
    - python
    - mdal
    - numpy
    - scikit-build
    - pip
    - cython
    - setuptools
  run:
    - python
    - mdal
    - meshio

test:
  commands:
    - python -c "import mdal"

about:
  home: https://www.mdal.xyz
  license: MIT
  license_file: LICENSE
  summary: Mesh Data Abstraction Library (MDAL) Python Integration
  description: |
    Mesh Data Abstraction Library (MDAL) is a C++ library for handling
    unstructured mesh data released with MIT license. It provides a single
    data model for multiple supported data formats. MDAL is used by QGIS
    for data access for mesh layers. This package provides the Python
    integration for MDAL.
  doc_url:  https://virgis-team.github.io/mdal-python/html/index.html
  dev_url: https://github.com/ViRGIS-Team/mdal-python

extra:
  recipe-maintainers:
    - runette
    - PeterPetrik
