{% set name = "mdal-python" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ViRGIS-Team/mdal-python
  #sha256: c3d84072c80d7d7f8f384539ca7290504b3c499aadba0d5fc1e2ed6eb11ed4ac
  
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
 
requirements:
  build:
    skip: True  # [py<39]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - cmake
  host:
    - python
    - mdal
    - numpy
    - scikit-build
    - pip
    - cython
  run:
    - python
    - mdal
    - meshio

test:
  commands:
    - python -c "import mdal"

about:
  home: https://www.mdal.xyz
  license: MIT
  license_file: LICENSE
  summary: Mesh Data Abstraction Library (MDAL) Python Integration
  description: |
    Mesh Data Abstraction Library (MDAL) is a C++ library for handling
    unstructured mesh data released with MIT license. It provides a single
    data model for multiple supported data formats. MDAL is used by QGIS
    for data access for mesh layers. This package provides the Python
    integration for MDAL.
  doc_url:  https://virgis-team.github.io/mdal-python/html/index.html
  dev_url: https://github.com/ViRGIS-Team/mdal-python

extra:
  recipe-maintainers:
    - runette
    - PeterPetrik
